name: Docker Image CI

on:
  push:
    branches:
      - docker

jobs:
  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOEKN }}
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vue-app:latest
