name: 标签触发的Docker镜像构建

on:
  push:
    tags:
      - 'v*'       # 监听以v开头的标签
      - 'text-v*'  # 监听以text-v开头的标签

jobs:
  build-and-push:
    name: 构建并推送Docker镜像
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: 提取标签名称
        id: get-tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: 登录阿里云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
      
      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/byzm/vue-app:${{ steps.get-tag.outputs.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 