name: 测试环境部署

on:
  push:
    branches:
      - test
    tags:
      - 'test-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: 提取元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ALI_REGISTRY }}/byzm/vue-app
          tags: |
            type=raw,value=test-latest,enable=${{ github.ref == 'refs/heads/test' }}
            type=ref,event=tag
            
      - name: 登录 阿里云
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALI_REGISTRY }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
